### ISSUE TITLE
serde_json::json! fails to parse integers above u64::MAX

### ISSUE THREAD

**Issue by Ech0riginal** [serde-rs/json#1258]
Per the title, serde_json's `json!` calls `unwrap` on an error'd Result somewhere in the macro when we give it an integer larger than u64's max size, giving us this message: 
```rust
Error("number out of range", line: 0, column: 0)
```
### Replication
```toml
[package]
name = "serde_json_u128"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { version = "1.0.140", features = [] }
```
```rust
fn main() {
    let bigint = u64::MAX;
    let biggerint = 123456789987654321123456789987654321u128;
    
    // This is fine
    let value_64 = serde_json::json!({ "@type" : "gx:BigDecimal", "@value" : bigint});
    // This is not
    let value_128 = serde_json::json!({ "@type" : "gx:BigDecimal", "@value" : biggerint});
}
```
