### ISSUE TITLE
Number type does not handle really big numbers

### ISSUE THREAD

**Issue by spease** [serde-rs/json#434]
I noticed this while sniffing DropBox LAN sync packets which were using a 39-digit "host_int" number. With the existing serde_json Number storage, only ~16 digits of precision are preserved as it saves it as a floating point. I wasn't able to try num_bigint::BigUint as the crates.io version hasn't upgraded to serde 1.0 yet (it looks like the github version may have).

To see the packets themselves, set up DropBox's LAN sync feature and then do:
```nc -lu 17500```

See also:
https://nmap.org/nsedoc/scripts/broadcast-dropbox-listener.html

**Comment by dtolnay** [comment]
Please try with the [`arbitrary_precision`](https://github.com/serde-rs/json/blob/4e6387f601d6eb54edcbcc0642d9523d4eb6998c/Cargo.toml#L41-L44) feature enabled.

```toml
[dependencies]
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
```
