### ISSUE TITLE
NaiveDateTime - Json deserialize error: input contains invalid characters

### ISSUE THREAD

**Issue by subhojit777** [serde-rs/json#531]
**`cargo.toml`**

```toml
actix-web = { version = "^0.7", features = ["ssl"] }
diesel = { version = "^1.4", features = ["mysql", "chrono", "r2d2"] }
dotenv = "0.13.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
chrono = { version = "0.4.6", features = ["serde"] }
futures = "^0.1"
env_logger = "^0.6"
failure = "^0.1.5"
```

**Model**:

```rust
#[derive(Deserialize, Serialize, Insertable, Debug)]
#[table_name = "answers"]
pub struct AnswerForm {
    pub question_id: i32,
    pub title: String,
    pub user_id: i32,
    pub created: NaiveDateTime,
}
```

**Schema**:

```sql
CREATE TABLE answers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  question_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  user_id INT NOT NULL,
  created TIMESTAMP NOT NULL
)
```

For a json input like this:

```json
{
    "question_id": 1,
    "title": "something",
    "user_id": 1,
    "created": "2007-04-05T14:30Z"
}
```

I am getting error:

```
Error occured during request handling: Json deserialize error: input contains invalid characters at line 5 column 34
```

---

This could be a problem in `chrono` I am not sure.
