### ISSUE TITLE
Error when using `serde_json::to_writer` to overwriting existing json file

### ISSUE THREAD

**Issue by v1nh1shungry** [serde-rs/json#894]
When I get an existing json file like this

```json
{
  "coding": false
}
```

and I want to change the value

```rust
use std::collections::HashMap;

fn main() {
    let mut map: HashMap<String, bool> = HashMap::new();
    let file = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .open("example.json").unwrap();
    map.insert(String::from("coding"), true);
    let _ = serde_json::to_writer_pretty(file, &map);
}
```

After I run `cargo run`, the content of the json file turns out to be

```json
{
  "coding": true
}}
```

`serde_json::to_writer` and `serde_json::to_writer_pretty` both have the same issues. If I write into a brand new file or the value of the key is already `true`, everything will be fine.

Here's the `Cargo.toml`

```toml
[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.81"
```

* platform: Manjaro
* rustc 1.61.0 (fe5b13d68 2022-05-18)

Can you reproduce this? Or have I misunderstood anything?
